### ISSUE TITLE
Ask for demo for this lib/script?

### ISSUE THREAD

**Issue by WindyWong** [monterail/angular-date-range-picker#20]
I can not find any demo for it, so I am not sure if this is what I want.  Can anyone provide me with a demo?  Thanks a lot!

**Comment by hodak** [comment]
Thanks for opening the issue. We're sorry to say that we've stopped maintaining this project in favor of [angular-mighty-datepicker](https://github.com/monterail/angular-mighty-datepicker). We encourage you to check it out instead.
