### ISSUE TITLE
Don't Want Dates Specified Within a Range

### ISSUE THREAD

**Issue by WindyWong** [monterail/angular-date-range-picker#21]
I see that you're using the range to automatically select two dates (I'd like to use the multiple calendar view). However, is there a way to pick a range of MONTHS that the calendar can choose dates within, and WITHOUT any dates selected by default? 

What I want to do is to have people specify start & end dates within a specific number of months without any dates already populated. Any way to do this? 

Thanks in advance for answering it!

**Comment by sirpeas** [comment]
Hello @WindyWong, we are no longer support date-range-picker, because we made new picker which can be find here https://github.com/monterail/angular-mighty-datepicker
Try to make range by using two simple mode pickers.
