### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by DaveC426913** [monterail/angular-date-range-picker#22]
It would be really cool if there were a little  more documentation.
For example, how do I actually *capture* the dates in my controller? How do I know they've changed?
I tried ng-click="ok($event)" but it does nothing.

[EDIT] The callback is what I was looking for. what would be very helpful if it were in the docs.

**Comment by Abhijeetpatil** [comment]
its a question Actully

I have to implement dateLimit how can i set limit to select two dates 

Thanks in Advance

**Comment by JackLeEmmerdeur** [comment]
Glad the Dave brought me on the right track. Looked up the location of callback within the datepicker-code. Found <b>scope { callback: "&" }</b> and as I knew that the isolated-scope mechanism in directives were a blind spot for me, I was forced to RTF. Thx to [this](http://weblogs.asp.net/dwahlin/creating-custom-angularjs-directives-part-2-isolate-scope), I could educate myself and as soon as I reached the &-symbol for isolated scopes I knew how to do it:

&lt;user ng-controller="UserCtrl"&gt;
&nbsp;&nbsp;&nbsp;&nbsp;&lt;input type="text" date-range-picker ng-model="dates" callback="onDatesChanged()" /&gt;

The input-element is contained within the directive <b>user</b>, which is bound to the Controller <b>UserCtrl</b>. The latter contains a function <b>$scope.onDatesChanged = function() {...</b>. So the date-range-picker gets the function passed into its isolated scope.

Maybe that was to detailed, but just alone the word callback could not help in the first place

**Comment by hodak** [comment]
Thanks for opening the issue. We're sorry to say that we've stopped maintaining this project in favor of [angular-mighty-datepicker](https://github.com/monterail/angular-mighty-datepicker). We encourage you to check it out instead.
