### ISSUE TITLE
Not working on Angular 1.3?

### ISSUE THREAD

**Issue by scotttrinh** [monterail/angular-date-range-picker#25]
Just upgraded to Angular 1.3, mostly for the native bind once, but looks like the date-range-picker isn't 1.3 compatible. Any plans to port it over soon?

**Comment by hodak** [comment]
Thanks for opening the issue. We're sorry to say that we've stopped maintaining this project in favor of [angular-mighty-datepicker](https://github.com/monterail/angular-mighty-datepicker). We encourage you to check it out instead.

**Comment by scotttrinh** [comment]
Looks good! I'll try it on my next project. :)
