### ISSUE TITLE
I have to implement dateLimit how can i set limit to select two dates 

### ISSUE THREAD

**Issue by Abhijeetpatil** [monterail/angular-date-range-picker#34]
its a question Actully

I have to implement dateLimit how can i set limit to select two dates 

Thanks in Advance

**Comment by sirpeas** [comment]
Hello @Abhijeetpatil, unfortunately we are no longer support angular-date-range-picker, I think that our new date picker will solve your problem. 
https://github.com/monterail/angular-mighty-datepicker
